version: "3.9"

services:
    renren-mysql:
        build: ./mysql
        volumes:
            - ./db_data:/var/lib/mysql

    renren-fast:
        build: ./renren-fast
        depends_on:
            - renren-mysql
        links:
            - "renren-mysql:renren-mysql"

    renren-fast-vue:
        build: ./renren-fast-vue
        ports:
            - "8080:8080"
        depends_on:
            - renren-fast
        links:
            - "renren-fast:renren-fast"